"""Helpers for generating organic-looking procedural shapes."""

from __future__ import annotations

import random
import math
from typing import List, Tuple

import pygame

Color = Tuple[int, int, int]


def _clamp(value: float, minimum: float, maximum: float) -> float:
    return max(minimum, min(maximum, value))


def generate_blob_mask(
    width: int,
    height: int,
    *,
    complexity: int = 10,
    angular_variation: float = 0.3,
    radial_variation: float = 0.35,
    seed: int | None = None,
) -> pygame.Mask:
    """Return a mask describing an irregular blob inside the given bounds.

    The blob is generated by walking around a circle and perturbing both the
    angle step and the radius for each vertex.  The resulting polygon is then
    rasterised into a :class:`pygame.Mask` so that it can be queried quickly.
    """

    if width <= 0 or height <= 0:
        raise ValueError("Blob dimensions must be positive")

    rng = random.Random(seed)
    points: List[Tuple[float, float]] = []

    complexity = max(5, complexity)
    base_radius = min(width, height) * 0.5
    angle = rng.uniform(0, math.tau)
    angle_step = math.tau / float(complexity)

    for _ in range(complexity):
        angle += angle_step * rng.uniform(1.0 - angular_variation, 1.0 + angular_variation)
        radius = base_radius * rng.uniform(1.0 - radial_variation, 1.0 + radial_variation)
        x = width * 0.5 + math.cos(angle) * radius
        y = height * 0.5 + math.sin(angle) * radius
        points.append((x, y))

    surface = pygame.Surface((width, height), pygame.SRCALPHA)
    if len(points) >= 3:
        pygame.draw.polygon(surface, (255, 255, 255, 255), points)
    else:
        pygame.draw.circle(surface, (255, 255, 255, 255), (width // 2, height // 2), int(base_radius))

    mask = pygame.mask.from_surface(surface)
    if mask.count() == 0:
        mask.fill()
    return mask


def jitter_color(color: Color, *, variance: int = 18) -> Color:
    """Return the colour with a small random offset applied to each channel."""

    rng = random.Random()
    return tuple(
        int(_clamp(channel + rng.randint(-variance, variance), 0, 255))
        for channel in color
    )  # type: ignore[return-value]


def mask_to_surface(mask: pygame.Mask, color: Color, alpha: int) -> pygame.Surface:
    """Convert ``mask`` into a per-pixel alpha surface tinted with ``color``."""

    surface = pygame.Surface(mask.get_size(), pygame.SRCALPHA)
    mask.to_surface(surface, setcolor=(*color, alpha), unsetcolor=(0, 0, 0, 0))
    return surface


def scatter_points(
    *,
    area: Tuple[int, int],
    count: int,
    jitter: float = 0.4,
) -> List[Tuple[float, float]]:
    """Generate clustered points that can be used as moss anchors."""

    width, height = area
    rng = random.Random()
    points: List[Tuple[float, float]] = []
    for _ in range(count):
        angle = rng.uniform(0, math.tau)
        radius = min(width, height) * rng.uniform(0.1, 0.5)
        radius *= 1.0 + rng.uniform(-jitter, jitter)
        cx = width * 0.5 + math.cos(angle) * radius
        cy = height * 0.5 + math.sin(angle) * radius
        points.append((cx, cy))
    return points


__all__ = ["generate_blob_mask", "jitter_color", "mask_to_surface", "scatter_points"]
