"""Configuration constants for the evolution simulation."""

import os
from pathlib import Path

WORLD_WIDTH = 4200
WORLD_HEIGHT = 2400
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 780

# Colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (124, 252, 184)
RED = (255, 150, 150)
BLUE = (150, 255, 150)
SEA = (194, 252, 250)
BACKGROUND = WHITE

# Simulation tuning parameters
N_LIFEFORMS = 100
N_VEGETATION = 100
N_DNA_PROFILES = 10
MAX_LIFEFORMS = 150
MUTATION_CHANCE = 5
MOSS_MUTATION_CHANCE = 0.2
MOSS_MUTATION_STRENGTH = 0.25
REPRODUCING_COOLDOWN_VALUE = 80
POPULATION_CAP_RETRY_COOLDOWN = 30

DNA_CHANGE_THRESHOLD = 0.1
COLOR_CHANGE_THRESHOLD = 0.1

GROUP_MIN_NEIGHBORS = 3
GROUP_MAX_RADIUS = 120
GROUP_COHESION_THRESHOLD = 0.35
GROUP_PERSISTENCE_FRAMES = 45
GROUP_MATURITY_RATIO = 0.6
BOID_ALIGNMENT_WEIGHT = 0.6
BOID_COHESION_WEIGHT = 0.45
BOID_SEPARATION_WEIGHT = 0.75
BOID_SEPARATION_DISTANCE = 48

MAX_WIDTH = 20
MIN_WIDTH = 8
MAX_HEIGHT = 20
MIN_HEIGHT = 8
MIN_MATURITY = 100
MAX_MATURITY = 500
VISION_MIN = 10
VISION_MAX = 80
DEGRADE_TIPPING = 3000

MEMORY_MAX_VISITED = 120
MEMORY_MAX_FOOD = 16
MEMORY_MAX_THREATS = 12
MEMORY_MAX_PARTNERS = 10
MEMORY_DECAY_MS = 45000
RECENT_VISIT_MEMORY_MS = 6000

HUNGER_SEEK_THRESHOLD = 320
HUNGER_CRITICAL_THRESHOLD = 520
ENERGY_REPRODUCTION_THRESHOLD = 0.68

WANDER_JITTER_DEGREES = 28
WANDER_INTERVAL_MS = 700

STUCK_FRAMES_THRESHOLD = 18
ESCAPE_OVERRIDE_FRAMES = 24
ESCAPE_FORCE = 1.8
OBSTACLE_LOOKAHEAD_BASE = 40
OBSTACLE_LOOKAHEAD_FACTOR = 6.0
OBSTACLE_AVOID_FORCE = 1.6
BOUNDARY_REPULSION_MARGIN = 80
BOUNDARY_REPULSION_WEIGHT = 1.25

FPS = 30

# Time-based tuning (per second rates)
AGE_RATE_PER_SECOND = 5.0
HUNGER_RATE_PER_SECOND = 3.5
ENERGY_RECOVERY_PER_SECOND = 18.0
WOUND_HEAL_PER_SECOND = 30.0
LONGEVITY_HEALTH_DECAY_PER_SECOND = 24.0
EXTREME_LONGEVITY_DECAY_PER_SECOND = 2400.0
HUNGER_HEALTH_PENALTY_PER_SECOND = 2.0
EXTREME_HUNGER_HEALTH_PENALTY_PER_SECOND = 20.0

# Debug logging
LOG_DIRECTORY = Path(os.getenv("EVOLUTION_LOG_DIR", "logs"))
DEBUG_LOG_FILE = os.getenv("EVOLUTION_DEBUG_LOG", "simulation_debug.log")
DEBUG_LOG_LEVEL = os.getenv("EVOLUTION_DEBUG_LOG_LEVEL", "INFO")

# Ant-style pheromone behaviour tuning
PHEROMONE_STRENGTH = 90.0
PHEROMONE_RADIUS = 48.0
PHEROMONE_EVAPORATION_RATE = 12.0  # per simulated second
FOLLOW_TRAIL_CHANCE = 0.65
HOME_RETURN_SPEED_MULTIPLIER = 1.35
PHEROMONE_DROP_INTERVAL_MS = 220
